<?php

namespace common\models;

/**
 * This is the ActiveQuery class for [[Accrual]].
 *
 * @see Accrual
 */
class AccrualQuery extends \yii\db\ActiveQuery
{
    use \common\models\DebtDateRestrictionTrait;

    /*public function active()
    {
        return $this->andWhere('[[status]]=1');
    }*/

    //public function init()
    public function prepare($builder)
    {
        //parent::init(); // TODO: Change the autogenerated stub
        $this->addDateRestriction('accrual_date');
        return parent::prepare($builder);
    }

    /**
     * @inheritdoc
     * @return Accrual[]|array
     */
    /*public function all($db = null)
    {
        $this->addDateRestriction('accrual_date');
        return parent::all($db);
    }

    public function count($q = '*', $db = null)
    {
        $this->addDateRestriction('accrual_date');
        return parent::count($q, $db);
    }*/

    /**
     * @inheritdoc
     * @return Accrual|array|null
     */
    /*public function one($db = null)
    {
        return parent::one($db);
    }*/
}
